=== jaliste/unitime/Documentation/Interfaces/CourseTimetable.dtd
<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<!ELEMENT arrangeTime EMPTY >
<!ATTLIST arrangeTime minPerWeek NMTOKEN #IMPLIED >

<!ELEMENT class ( class*, date*, (time|arrangeTime)?, (room|location)*, instructor* ) >
<!ATTLIST class courseNbr NMTOKEN #REQUIRED >
<!ATTLIST class id CDATA #IMPLIED >
<!ATTLIST class scheduleNote CDATA #IMPLIED >
<!ATTLIST class subject CDATA #REQUIRED >
<!ATTLIST class suffix NMTOKEN #REQUIRED >
<!ATTLIST class type NMTOKEN #REQUIRED >

<!ELEMENT date EMPTY >
<!ATTLIST date endDate CDATA #REQUIRED >
<!ATTLIST date startDate CDATA #REQUIRED >

<!ELEMENT instructor EMPTY >
<!ATTLIST instructor fname CDATA #IMPLIED >
<!ATTLIST instructor id NMTOKEN #REQUIRED >
<!ATTLIST instructor lead ( false | true ) #IMPLIED >
<!ATTLIST instructor lname CDATA #IMPLIED >
<!ATTLIST instructor mname CDATA #IMPLIED >
<!ATTLIST instructor share NMTOKEN #REQUIRED >

<!ELEMENT room EMPTY >
<!ATTLIST room building NMTOKEN #REQUIRED >
<!ATTLIST room id CDATA #IMPLIED >
<!ATTLIST room roomNbr NMTOKEN #REQUIRED >

<!ELEMENT location EMPTY >
<!ATTLIST location name CDATA #REQUIRED >

<!ELEMENT time EMPTY >
<!ATTLIST time days NMTOKEN #REQUIRED >
<!ATTLIST time endTime NMTOKEN #REQUIRED >
<!ATTLIST time startTime NMTOKEN #REQUIRED >

<!ELEMENT timetable ( class+ ) >
<!ATTLIST timetable action CDATA #REQUIRED >
<!ATTLIST timetable campus NMTOKEN #REQUIRED >
<!ATTLIST timetable year NMTOKEN #REQUIRED >
<!ATTLIST timetable term NMTOKEN #REQUIRED >

=== jaliste/unitime/Documentation/Interfaces/Examples/courseTimetableExport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE timetable PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/CourseTimetable.dtd">

<!-- 
 * UniTime 3.0 (University Course Timetabling & Student Sectioning Application)
 * Copyright (C) 2007, UniTime.org
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 -->

<timetable action="update|???" campus='puWestLafayetteTrdtn' year='2007' term='Fal'>
	<class id="" subject="A&amp;AE" courseNbr="101" type="Lec" suffix="1" scheduleNote="">
		<date startDate="08/20" endDate="09/22"/> <!-- non-default date pattern -->
		<time days="MWF" startTime="0730" endTime="0820"/>
		<room id="" building="REC" roomNbr="101"/>
		<room id="" building="REC" roomNbr="102"/>
		<instructor id="23344" lname="" mname="" fname="" share="0.8" lead="true"/> <!-- only instructors that are allowed to be printed are included -->
		<instructor id="23435" lname="" mname="" fname="" share="0.2"/>
	</class>
	<class id="" subject="A&amp;AE" courseNbr="101" type="Lec" suffix="1" scheduleNote="">
		<arrangeTime minPerWeek="100"/> <!-- arrange hours class -->
		<room id="" building="REC" roomNbr="102"/>
		<instructor id="23344" lname="" mname="" fname="" share="1.0"/>
	</class>
	<class id="" subject="A&amp;AE" courseNbr="102" type="Lec" suffix="1" scheduleNote="">
		<time days="TTh" startTime="1030" endTime="1220"/>
		<location name="PIZZA HUT"/> <!-- non university location -->
		<instructor id="23344" lname="" mname="" fname="" share="1.0"/>
	</class>
	<!-- ... -->
</timetable>
