=== jaliste/unitime/Documentation/Interfaces/menu.dtd
<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2011, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->
 
<!ELEMENT unitime-menu (menu|item|separator)* >
 
<!ELEMENT menu (condition?, (menu|item|separator)*) >
<!ATTLIST menu name CDATA #REQUIRED >
<!ATTLIST menu title CDATA #IMPLIED >
<!ATTLIST menu page CDATA #IMPLIED >
<!ATTLIST menu type (gwt|property) #IMPLIED >
<!ATTLIST menu target (download|dialog) #IMPLIED >
 
<!ELEMENT separator (condition?) >

<!ELEMENT item (condition?) > 
<!ATTLIST item name CDATA #REQUIRED >
<!ATTLIST item page CDATA #REQUIRED >
<!ATTLIST item type (gwt|property) #IMPLIED >
<!ATTLIST item target (download|dialog) #IMPLIED >

<!ELEMENT condition (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight)* >

<!ELEMENT and (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight)* >
<!ELEMENT or (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight)* >
<!ELEMENT not (and|or|not|isAuthenticated|hasRole|hasProperty|propertyEquals|hasRight)* >
 
 <!ELEMENT isAuthenticated EMPTY >
 
<!ELEMENT hasRole EMPTY >
<!ATTLIST hasRole name CDATA #IMPLIED >

<!ELEMENT hasProperty EMPTY >
<!ATTLIST hasProperty name CDATA #REQUIRED >

<!ELEMENT propertyEquals EMPTY >
<!ATTLIST propertyEquals name CDATA #REQUIRED >
<!ATTLIST propertyEquals value CDATA #REQUIRED >
<!ATTLIST propertyEquals defaultValue CDATA #IMPLIED >

<!ELEMENT hasRight EMPTY >
<!ATTLIST hasRight name (canSeeCourses|canSeeTimetable|hasASolverGroup|canDoTimetable|canAudit|canSectionStudents|isSectioningEnabled|isRegistrationEnabled|canSeeEvents|isChameleon|hasPersonalReport|isStudent|hasRoomAvailability|canSeeExams|canTimetableExams) #REQUIRED >

=== jaliste/unitime/JavaSource/menu.xml
<?xml version="1.0"?>
<!DOCTYPE unitime-menu PUBLIC "-//UniTime//UniTime Menu DTD/EN" "http://www.unitime.org/interface/menu.dtd">

<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->
<unitime-menu>
	<menu name="Courses" title="Course Timetabling">
		<condition>
			<isAuthenticated/>
			<or>
				<propertyEquals name="tmtbl.menu.display_course_timetabling" value="true" defaultValue="true"/>
				<hasRole name="Administrator"/>
			</or>
			<hasRight name="canSeeCourses"/>
		</condition>
		<menu name="Input Data" title="Course Timetabling Input Data">
			<item name="Instructional Offerings" page="instructionalOfferingShowSearch.do"/>
			<item name="Classes" page="classShowSearch.do"/>
			<separator/>
			<menu name="Curricula" page="curricula" type="gwt">
				<item name="Projection Rules" page="curprojrules" type="gwt"/>
			</menu>
			<separator/>
			<menu name="Instructors" page="instructorSearch.do">
				<item name="Designator List" page="designatorList.do"/>
			</menu>
			<separator/>
			<menu name="Rooms" page="roomSearch.do">
				<item name="Room Features" page="roomFeatureSearch.do"/>
				<item name="Room Groups" page="roomGroupSearch.do"/>
			</menu>
			<separator/>
			<item name="Distribution Preferences" page="distributionPrefs.do"/>
			<menu name="Reservations" page="reservations" type="gwt"/>
			<item name="Class Assignments" page="classAssignmentsReportShowSearch.do">
				<condition>
					<hasRight name="canSeeTimetable"/>
				</condition>
			</item>
		</menu>
		<menu name="Course Timetabling" title="Course Timetabling Solver">
			<condition>
				<hasRight name="hasASolverGroup"/>
				<hasRight name="canSeeTimetable"/>
				<hasRight name="canDoTimetable"/>
			</condition>
			<item name="Saved Timetables" page="listSolutions.do"/>
			<item name="Solver" page="solver.do"/>
			<item name="Timetable Grid" page="timetable.do"/>
			<separator/>
			<item name="Assigned Classes" page="assignedClasses.do"/>
			<item name="Not-assigned Classes" page="unassigned.do"/>
			<item name="Changes" page="solutionChanges.do"/>
			<item name="History" page="assignmentHistory.do"/>
			<item name="Conflict Statistics" page="cbs.do"/>
			<item name="Solver Log" page="solverLog.do"/>
			<item name="Reports" page="solutionReport.do"/>
			<separator>
				<condition>
					<hasRole name="Administrator"/>
				</condition>
			</separator>
			<item name="Manage Solvers" page="manageSolvers.do">
				<condition>
					<hasRole name="Administrator"/>
				</condition>
			</item>
		</menu>
		<menu name="Course Timetabling" title="Course Timetabling Solver">
			<condition>
				<hasRight name="hasASolverGroup"/>
				<hasRight name="canSeeTimetable"/>
				<not>
					<hasRight name="canDoTimetable"/>
				</not>
			</condition>
			<item name="Saved Timetables" page="listSolutions.do"/>
			<item name="Timetable Grid" page="timetable.do"/>
		</menu>
		<menu name="Course Audit" title="Course Timetabling Audit">
			<condition>
				<hasRight name="hasASolverGroup"/>
				<not>
					<hasRight name="canSeeTimetable"/>
				</not>
				<hasRight name="canAudit"/>
			</condition>
			<item name="Solver" page="solver.do"/>
			<item name="Conflict Statistics" page="cbs.do"/>
			<item name="Solver Log" page="solverLog.do"/>
			<item name="Reports" page="solutionReport.do"/>
		</menu>
		<item name="Reports" page="hql&amp;appearance=courses" type="gwt">
			<condition>
				<hasRight name="hasCourseReports"/>
			</condition>
		</item>
	</menu>
	<menu name="Curricula" title="Curriculum Timetabling">
		<condition>
			<hasRole name="Curriculum Mgr"/>
		</condition>
		<item name="Curricula" page="curricula" type="gwt"/>
		<item name="Projection Rules" page="curprojrules" type="gwt"/>
	</menu>
	<menu name="Students">
		<condition>
			<or>
				<propertyEquals name="tmtbl.menu.display_student_sectioning" value="true" defaultValue="true"/>
				<hasRole name="Administrator"/>
			</or>
			<hasRight name="canSectionStudents"/>
		</condition>
		<menu name="Batch Solver" page="studentSolver.do">
			<item name="Solver Log" page="studentSolverLog.do"/>
			<item name="Solver Dashboard" page="batchsctdash" type="gwt"/>
		</menu>
		<separator>
			<condition>
				<or>
					<hasRight name="isSectioningEnabled"/>
					<hasRight name="isRegistrationEnabled"/>
				</or>
			</condition>
		</separator>
		<item name="Scheduling Assistant" page="sectioning" type="gwt">
			<condition>
				<hasRight name="isSectioningEnabled"/>
			</condition>
		</item>
		<item name="Online Scheduling Dashboard" page="onlinesctdash" type="gwt">
			<condition>
				<hasRight name="isSectioningEnabled"/>
			</condition>
		</item>
		<item name="Course Requests" page="requests" type="gwt">
			<condition>
				<hasRight name="isRegistrationEnabled"/>
			</condition>
		</item>
		<separator/>
		<item name="Enrollment Audits" page="enrollmentAuditPdfReport.do"/>
		<item name="Reports" page="hql&amp;appearance=sectioning" type="gwt">
			<condition>
				<hasRight name="hasStudentReports"/>
			</condition>
		</item>
	</menu>
	<menu name="Examinations">
		<condition>
			<or>
				<propertyEquals name="tmtbl.menu.display_exam_timetabling" value="true" defaultValue="true"/>
				<hasRole name="Administrator"/>
			</or>
			<hasRight name="canSeeExams"/>
		</condition>
		<menu name="Input Data">
			<item name="Instructors" page="instructorSearch.do"/>
			<separator/>
			<menu name="Rooms" page="roomSearch.do?default=Exam">
				<item name="Room Features" page="roomFeatureSearch.do?default=Exam"/>
				<item name="Room Groups" page="roomGroupSearch.do?default=Exam"/>
				<item name="Room Availability" page="roomAvailability.do">
					<condition>
						<hasRight name="hasRoomAvailability"/>
					</condition>
				</item>
			</menu>
			<separator/>
			<item name="Examinations" page="examList.do"/>
			<item name="Distribution Preferences" page="examDistributionPrefs.do"/>
		</menu>
		<menu name="Examination Timetabling">
			<condition>
				<hasRight name="canTimetableExams"/>
			</condition>
			<item name="Examination Solver" page="examSolver.do"/>
			<item name="Timetable Grid" page="examGrid.do"/>
			<separator/>
			<item name="Assigned Exams" page="assignedExams.do"/>
			<item name="Not-assigned Exams" page="unassignedExams.do"/>
			<item name="Changes" page="examChanges.do"/>
			<item name="Conflict Statistics" page="ecbs.do"/>
			<item name="Solver Log" page="examSolverLog.do"/>
			<separator/>
			<item name="Reports" page="examAssignmentReport.do"/>
		</menu>
		<item name="Pdf Reports" page="examPdfReport.do">
			<condition>
				<or>
					<hasRole name="Administrator"/>
					<hasRole name="Exam Mgr"/>
				</or>
			</condition>
		</item>
		<item name="Reports" page="hql&amp;appearance=exams" type="gwt">
			<condition>
				<hasRight name="hasExamReports"/>
			</condition>
		</item>
	</menu>
	<item name="Classes" page="classes.do">
		<condition>
			<or>
				<not>
					<isAuthenticated/>
				</not>
				<not>
					<hasRole/>
				</not>
			</or>
		</condition>
	</item>
	<item name="Examinations" page="exams.do">
		<condition>
			<or>
				<not>
					<isAuthenticated/>
				</not>
				<not>
					<hasRole/>
				</not>
			</or>
		</condition>
	</item>
	<item name="Timetable" page="timetable" type="gwt">
		<condition>
			<and>
				<not>
					<isAuthenticated/>
				</not>
				<propertyEquals name="unitime.event_timetable.requires_authentication" value="false" defaultValue="true"/>
			</and>
		</condition>
	</item>
	<menu name="Events">
		<condition>
			<or>
				<propertyEquals name="tmtbl.menu.display_event_management" value="true" defaultValue="true"/>
				<hasRole name="Administrator"/>
			</or>
			<hasRight name="canSeeEvents"/>
		</condition>
		<menu name="Rooms" page="roomSearch.do?default=Exam">
			<condition>
				<hasRole name="Event Mgr"/>
			</condition>
			<item name="Room Features" page="roomFeatureSearch.do"/>
			<item name="Room Groups" page="roomGroupSearch.do"/>
		</menu>
		<separator>
			<condition>
				<hasRole name="Event Mgr"/>
			</condition>
		</separator>
		<item name="Events" page="eventList.do"/>
		<item name="Meetings" page="meetingList.do"/>
		<item name="Add Event" page="eventAdd.do"/>
		<item name="Room Availability" page="eventGrid.do"/>
		<separator/>
		<item name="Timetable" page="timetable" type="gwt" />
		<item name="Reports" page="hql&amp;appearance=events" type="gwt">
			<condition>
				<hasRight name="hasEventReports"/>
			</condition>
		</item>
	</menu>
	<item name="Course Requests" page="requests" type="gwt">
		<condition>
			<and>
				<or>
					<hasRight name="isStudent"/>
					<hasRole name="Advisor"/>
				</or>
				<hasRight name="isRegistrationEnabled"/>
			</and>
		</condition>
	</item>
	<item name="Scheduling Assistant" page="sectioning" type="gwt">
		<condition>
			<and>
				<or>
					<not>
						<isAuthenticated/>
					</not>
					<and>
						<not>
							<hasRole/>
						</not>
						<hasRight name="isStudent"/>
					</and>
					<hasRole name="Advisor"/>
				</or>
				<hasRight name="isSectioningEnabled"/>
			</and>
		</condition>
	</item>
	<item name="Scheduling Dashboard" page="onlinesctdash" type="gwt">
		<condition>
			<or>
				<hasRight name="isInstructor"/>
				<hasRole name="Dept Sched Mgr"/>
				<hasRole name="Advisor"/>
			</or>
			<hasRight name="isSectioningEnabled"/>
		</condition>
	</item>
