=== jaliste/unitime/Documentation/Interfaces/StudentCourse.dtd
<!-- 
 * UniTime 3.2 (University Timetabling Application)
 * Copyright (C) 2008 - 2010, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->

<!ELEMENT studentCourse EMPTY >
<!ATTLIST studentCourse courseNumber CDATA #IMPLIED >
<!ATTLIST studentCourse externalId NMTOKEN #IMPLIED >
<!ATTLIST studentCourse priority NMTOKEN #REQUIRED >
<!ATTLIST studentCourse subject CDATA #IMPLIED >

<!ELEMENT lastLikeCourseDemand ( student+ ) >
<!ATTLIST lastLikeCourseDemand campus NMTOKEN #REQUIRED >
<!ATTLIST lastLikeCourseDemand created CDATA #IMPLIED >
<!ATTLIST lastLikeCourseDemand term NMTOKEN #REQUIRED >
<!ATTLIST lastLikeCourseDemand year NMTOKEN #REQUIRED >

<!ELEMENT student ( studentCourse+ ) >
<!ATTLIST student externalId NMTOKEN #REQUIRED >

=== jaliste/unitime/Documentation/Interfaces/Examples/studentCrsDemandImport.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lastLikeCourseDemand PUBLIC "-//UniTime//DTD University Course Timetabling/EN" "http://www.unitime.org/interface/StudentCourse.dtd">

<!-- 
 * UniTime 3.0 (University Course Timetabling & Student Sectioning Application)
 * Copyright (C) 2007, UniTime.org
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program; if not, write to the Free Software Foundation, Inc.,
 * 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
 -->

	<!-- student ==>         Required:  externalId
	       studentCourse ==> [1 ==> N entries]
	                         Required:  subject, courseNumber, priority
	-->
<lastLikeCourseDemand campus="puWestLafayetteTrdtn" term="Fal" year="2007">
 	<student externalId="9999111110">
  		<studentCourse subject="C E" courseNumber="699A" priority="1"/>
 	</student>
 	<student externalId="9999111111">
  		<studentCourse subject="V M" courseNumber="206" priority="1"/>
   		<studentCourse subject="V M" courseNumber="220" priority="2"/>
   		<studentCourse subject="V M" courseNumber="245" priority="3"/>
   		<studentCourse subject="VPB" courseNumber="225" priority="4"/>
   		<studentCourse subject="V M" courseNumber="227" priority="5"/>
 	</student>
</lastLikeCourseDemand>
