=== jaliste/unitime/Documentation/Interfaces/StudentScheduling_3_4.dtd
<!-- 
 * UniTime 3.4 (University Timetabling Application)
 * Copyright (C) 2012, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->
 
<!--
 - Student Scheduling XML interface
   - this interface is to be used to synchronize student information with an external system during (online) student scheduling
   - it also contains ability for the external system to approve / reject changes in student's schedule (an ability of a student to get into a course)
 - See studentSchedulingSynchronization.xml for an example and a desription.
 - Since UniTime 3.4
-->
 
<!ELEMENT message (student+) >
<!ATTLIST message id CDATA #REQUIRED >
<!ATTLIST message repliesTo CDATA #IMPLIED >
<!ATTLIST message created CDATA #REQUIRED >
<!ATTLIST message type ( student_change | approval_request | approval | consent | synchronization | schedule_change ) #REQUIRED >
<!ATTLIST message source ( assistant | waitlist | course_change | dashboard | synchronization | student_change )  #IMPLIED >
<!ATTLIST message tsformat CDATA #IMPLIED >

<!ELEMENT student (curriculum*, group*, course*) >
<!ATTLIST student id CDATA #REQUIRED >
<!ATTLIST student first CDATA #IMPLIED >
<!ATTLIST student middle CDATA #IMPLIED >
<!ATTLIST student last CDATA #IMPLIED >
<!ATTLIST student email CDATA #IMPLIED >
<!ATTLIST student status CDATA #IMPLIED >

<!ELEMENT curriculum EMPTY >
<!ATTLIST curriculum area CDATA #REQUIRED >
<!ATTLIST curriculum major CDATA #REQUIRED >
<!ATTLIST curriculum minor CDATA #IMPLIED >
<!ATTLIST curriculum classification CDATA #REQUIRED >

<!ELEMENT group EMPTY >
<!ATTLIST group code CDATA #REQUIRED >

<!ELEMENT course (class*) >
<!ATTLIST course subject CDATA #REQUIRED >
<!ATTLIST course number CDATA #REQUIRED >
<!ATTLIST course status CDATA #IMPLIED >
<!ATTLIST course message CDATA #IMPLIED >
<!ATTLIST course consent CDATA #IMPLIED >
<!ATTLIST course request CDATA #IMPLIED >
<!ATTLIST course priority CDATA #IMPLIED >
<!ATTLIST course force ( true | false ) #IMPLIED >

<!ELEMENT class ( #PCDATA ) >
<!ATTLIST class id CDATA #IMPLIED >
<!ATTLIST class enrollment CDATA #IMPLIED >

=== jaliste/unitime/Documentation/Interfaces/Examples/studentSchedulingSynchronization.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE message PUBLIC "-//UniTime//Student Sectioning Interface/EN" "http://www.unitime.org/interface/StudentScheduling_3_4.dtd">

<!-- 
 * UniTime 3.4 (University Timetabling Application)
 * Copyright (C) 2012, UniTime LLC
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 3 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License along
 * with this program.  If not, see <http://www.gnu.org/licenses/>.
 * 
 -->
 
 <!--
 - Student Scheduling XML interface
   - this interface is to be used to synchronize student information with an external system during (online) student scheduling
   - it also contains ability for the external system to approve / reject changes in student's schedule (an ability of a student to get into a course)
 - Since UniTime 3.4
-->

<message id="10234" repliesTo="10232" created="2012/04/17 6:46:10" type="schedule_change" source="assistant" tsformat="yyyy/MM/dd HH:mm:ss">
    <!-- id .. generated unique message id -->
    <!-- repliesTo .. if the message is a response to some other message, this contains id of the other message -->
    <!-- created .. time stamp in some given format -->
    <!-- type .. message type: schedule change, approval request, consent, synchronization, approval, student change -->
    <!-- source .. message source (for UniTime side): assistant, wait-list, course change, dashboard, nightly synchronization, student change (optional) -->
    <!-- tsformat .. time stamp format -->
    <student id="120345679" first="Joe" middle="Franklin" last="Doe" email="doe@university.edu" status="2012/04/01 12:23:23 scheduling">
        <!-- id .. student external id -->
        <!-- first, middle, last .. student name -->
        <!-- email .. student email -->
        <!-- status .. student status reference (+ time of the last change) -->
        <curriculum area="A" major="VSC" classification="01"/>
        <!-- curriculum information, multiple curricula can be provided -->
        <group code="YngExpl"/>
        <!-- multiple student groups may be present -->
        
        <!-- student schedule: -->
        <course subject="AAE" number="20300" status="approved">
            <class id="12456"/>
            <class id="12424"/>
            <!-- subject, number .. course identification -->
            <!-- status .. approval status: approved, pending, rejected (only from Banner to UniTime) -->
            <!--   statuses to be defined in a lookup table, generated by Banner in a response to UniTime approval request / schedule change messages -->
            <!-- class id .. external id (CRN) of the class -->
        </course>
        <course subject="ENGL" number="10600R" status="pending" message="Instructor signature needed">
            <!-- status, message .. last provided status and message (optional) from Banner approval process -->
            <class id="234095"/>
            <class id="234054"/>
            <class id="230065"/>
            <class>230065</class>
        </course>
        <course subject="BIOL" number="10500" status="reject" message="prereq not met"/>
        <!-- example reject response from Banner -->
        <!-- if message is not provided, the default one from the status lookup table is given -->
        <!-- status lookup table: banner status -> approve / reject / pending + default message to student -->
        <course subject="CS" number="25400">
            <!-- new course (no approval status was provided by Banner yet) -->
            <class id="213435"/>
        </course>
        <course subject="AAE" number="20400" consent="2012/04/16 14:23:20 23456435">
            <class id="231235"/>
            <!-- consent of instructor / department was given, consent contains timestamp in a given format + space + external id of the person who gave consent -->
        </course>
        <!-- Do we need to list courses, classes that were removed from student schedule (from UniTime), either by student, automatic scheduling, or by rejecting consent? -->
        <!-- Do we want to include timestamp?
           when a course was requested
           when a class was given to the student in UniTime
           when approval status was given / changed         
        -->
        <!-- Do we want to include external id of the person who did make the change (if it was not automated)?
           Or just one of: student, advisor (any person, not student), system (automatic)
           This we know on a course request and on the enrollment
         -->
        <!-- Do we want to include priority / alternativity of the course request? -->
        <!-- Do we want to include wait-listed (not assigned) course requests in the student schedule? probably not -->
        <course subject="AAE" number="30100" request="2012/04/16 12:23:12 120345679" consent="2012/04/17 8:12:21 23456435" priority="1A" status="2012/04/17 8:14:23 approved">
            <class id="340920" enrollment="2012/04/16 12:23:12 120345679"/>
            <!-- enrollment, if no external id is present (just a timestamp), the enrollment was made by the system (course change or wait-list processing) -->
        </course>
    </student>
            
    <!-- student schedule change example -->
    <!-- request sent from UniTime -->
    <!-- message id="1243214" created="2012/04/17 09:19:10" type="schedule change" source="assistant" -->
    <student id="120345679" first="Joe" middle="Franklin" last="Doe" email="doe@university.edu" status="2012/04/01 12:23:23 scheduling">
        <curriculum area="A" major="VCS" classification="01"/>
        <!-- course with no change -->
        <course subject="AAE" number="20300" request="2012/04/14 17:11:10 120345679" status="2012/04/14 17:12:10 approved" priority="1">
            <class id="12456" enrollment="2012/04/14 17:11:10 120345679"/>
            <class id="12424" enrollment="2012/04/14 17:11:10 120345679"/>
        </course>
        <course subject="AAE" number="20400" request="2012/04/14 17:11:10 120345679" status="2012/04/14 17:12:10 approved" consent="2012/04/16 14:23:20 23456435" priority="2">
            <class id="231235" enrollment="2012/04/14 17:11:10 120345679"/>
        </course>
        <!-- new course -->
        <course subject="AAE" number="30100" request="2012/04/17 09:19:10 120345679" priority="3" force="true">
        	<!-- if force attribute is there and set to true, Banner must accept -->
            <class id="340920" enrollment="2012/04/17 09:19:10 120345679"/>
        </course>
        <!-- class schedule change, in a pending state -->
        <course subject="ENGL" number="10600R" request="2012/04/14 17:11:10 120345679" status="2012/04/14 17:12:10 pending" message="Instructor signature needed" priority="4A">
            <class id="234095" enrollment="2012/04/14 17:11:10 120345679"/>
            <class id="234054" enrollment="2012/04/17 09:19:10 120345679"/>
            <class id="230065" enrollment="2012/04/17 09:19:10 120345679"/>
        </course>
    </student>
    <!-- response sent from Banner -->
    <!-- message id="1243134" repliesTo="1243214" created="2012/04/17 09:21:15" type="approval" -->
    <student id="120345679" first="Joe" middle="Franklin" last="Doe" email="doe@university.edu" status="scheduling">
        <curriculum area="A" major="VCS" classification="01"/>
        <course subject="AAE" number="20300" status="approved"/>
        <!-- class assignments are not needed -->
        <course subject="AAE" number="20400" status="approved"/>
        <course subject="AAE" number="30100" status="approved"/>
        <course subject="ENGL" number="10600R" status="pending" message="Instructor signature needed"/>
    </student>
    
    <!-- student update message from Banner -->
    <!-- message id="1243324" created="2012/04/17 09:25:21" type="student change" -->
    <student id="120345679" first="Joe" middle="Franklin" last="Doe" email="doe@university.edu" status="scheduling">
        <curriculum area="A" major="VCS" classification="01"/>
    </student>
    <!-- if there is some pending / not yet approved course, UniTime will response with a request message -->
    <!-- message id="12432455" repliesTo="1243324" created="2012/04/17 09:27:12" type="approval request" source="student change" -->
    <!-- same content as the schedule change example above -->
</message>
